name: Build App

on:
    
  workflow_dispatch:

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build to exe
      run: |
        pyinstaller --onefile app.py   
    - name: "Make executable"
      run: |
        cd dist
        chmod +x run
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name:  buildLinux
        path: |
          dist/app
  BuildForMac:
    runs-on: windows-latest
    permissions:
      contents: write
      
    steps:
      - name: Prepare Checkout
        uses: actions/checkout@v3
      - name: Prepare Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build to exe
        run: |
          pyinstaller --onefile app.py
      - name: List dist
        run: |
          cd dist
          ls
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name:  buildWindows
          path: |
            dist/app.exe
  Release:
    runs-on: ubuntu-latest
    needs: [BuildForMac, build]
    steps:
      - name: Prepare Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: buildLinux
          path: |
            dist/app
      - uses: actions/download-artifact@master
        with:
          name: buildWindows
          path: |
            dist/app.exe
      - name: List
        run: ls
      - name: "Create Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: |
            dist/app
            dist/app.exe
            buildfiles/LICENSE.txt
